activecampaign.php
Use protocol relative url when loading remote resource to prevent SSL errors.
=> Use of protocol relative url

form_process.php
Related to [this pull request](https://github.com/ActiveCampaign/activecampaign-api-php/pull/24).
We need session started here in case they are using a captcha in their subscription form along with the Ajax option. The script then looks for `$_SESSION["image_random_value"]` in the PHP API library.
[#96562044]
=> Form captcha verify via Ajax

form_process.php
We can't rely on a session var to tell us if captcha is in the form. Instead we have to scan the form HTML for it. This way if you submit the API request outside of the browser, you can't bypass the captcha check just because you don't have the session var set.
[Related to this pull request](https://github.com/ActiveCampaign/activecampaign-api-php/pull/24/files#r32753810).
[#96562044]
=> Detect captcha from the form HTML

readme.txt
Shortened the description because it was being cut-off on the [main WordPress plugin page](https://wordpress.org/plugins/activecampaign-subscription-forms/).
=> Shortened WordPress plugin description

activecampaign-api-php/Connector.class.php
We don't need this for connecting with AC API URL's. It can cause a `open_basedir` server error on some servers.
=> Get rid of followlocation [#112000725]

README.md, readme.txt
Show the Changelog and Upgrade Notice in descending order (too hard to read in the WordPress interface otherwise).
No story involved - quick fix after seeing [this comment](https://wordpress.org/support/topic/release-notes-4?replies=1#post-8013689).
=> Changelog and upgrade notice sort order

activecampaign.php
If the WordPress site is using SSL, and the AC account uses a CNAME, the JS embed request would try to load the SSL version of the CNAME, which we can't rely on. So now we always save the true `activehosted.com` domain within their settings, then we can always use that when embedding the forms.
=> Form embed fix for SSL [#114229331]

README.md, activecampaign.php, readme.txt
This was an issue in 2 parts, one on our end, one is a bug/oversight in Live Composer that I have had to work around.
We only load the scripts for AC forms in the backend editing pages, but there are plugins that can let you edit pages from anywhere. Now, any time we initialise the AC form buttons, we also load the backend scripts that will make them work.
Live Composer loads all HTML from changes before saving them, and will break if any JS errors happen when loading this content. However, when you dynamically insert HTML with script tags into a web page, they will run in the order they are finished loading, and not sequentially. This causes JS errors, that blocks Live Composer from updating.
I added a check to see if we are loading the AC form buttons dynamically, and if so, load the …
=> Cannot insert AC forms with Live Composer plugin [#114529991]

README.md, readme.txt
Included the upgrade notice message within the changelog since it doesn't show up when the plugin has a new version available. Example: http://screen.ac/0P14340b3l39
=> WordPress plugin upgrade notice [#115362467]

activecampaign-api-php/Connector.class.php
Added support for WordPress servers that don't have PHP `curl` installed. In this case we fall back to the native WordPress HTTP methods.
=> WordPress curl check [#115968513]

activecampaign-api-php/Connector.class.php
Always use WordPress native HTTP library, instead of PHP `cURL`. We've seen too many cases where the user's server is not receiving data back from the `cURL` response, even though their server supports `cURL`.
=> WordPress curl check [#116975277]

activecampaign.php
Append a unique string onto the end of the JS embed URL, so the browser doesn't load a cached copy. This can happen if the same form embed JS code appears on the page more than once.
=> Multiple form embed fix [#117174419]

activecampaign-api-php/Connector.class.php
There is a current issue when the error being pushed by WordPress isn't being displayed properly... We should actually display these errors instead of something the user won't understand.
=> [#121310657] WP_Error Display issue

README.md, activecampaign-api-php/Connector.class.php, activecampaign.php, readme.txt
Normally `$response` is an array, so we also have to check if it's an object.
Otherwise we get this PHP warning:
`Warning: get_class() expects parameter 1 to be object, array given`
=> WordPress error check fix [#121310657]

README.md, activecampaign.php, readme.txt
This fixes the `Undefined index: css` error, which would happen when a specific form being embedded doesn't have a CSS setting saved for it.
=> Fix for undefined index error [#128131397]

README.md, activecampaign.php, readme.txt
Remove ActiveCampaign account data from showing in JS for site tracking. It should only show what's needed for site tracking to work.
@cristiangrama
=> Limit account data shown in JS for site tracking DEVJIRA-3437 

README.md, activecampaign.php, readme.txt
Fix for when 'site_tracking' is undefined (we assumed it was always set). It won't be set if the checkbox is not checked on the ActiveCampaign settings page.
@cristiangrama Please review, thanks! 👍
=> site_tracking undefined fix DEVJIRA-4031

README.md, activecampaign.php, admin_styles.css, readme.txt, site_tracking.js
Added new site tracking settings options for GDPR:
This provides users with the option to track (or don't track) by default. If "do not track by default" is chosen, it is up to the WordPress user to initiate tracking requests using our custom JavaScript functions.
**Team:** @ActiveCampaign/integration
=> Add new Site Tracking options for GDPR INT-354

README.md, activecampaign.php, readme.txt
Upgrade version so users on 6.25 are prompt/aware of the upgrade.
The latest version (6.3) is technically smaller than 6.25 in semantic versioning so users on 6.25 won't ever see an upgrade prompt unless we got to 6.25.1 or 6.26.
**Team:** @ActiveCampaign/integration
=> Version 7.0: Force upgrade prompt for users on 6.25 INT-416

activecampaign-api-php/Connector.class.php
Set our own Host Header on requests instead of the default WordPress one.
=> Set our own host header on requests
